project_id = "gozussastelqyolweech"

[functions.create-subscription]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.delete-user-admin]
verify_jwt = true

[functions.generate-sample-data]
verify_jwt = true

[functions.import-openopus-data]
verify_jwt = true

[functions.send-upgrade-request]
verify_jwt = true

[functions.send-upgrade-reminder]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true