// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gozussastelqyolweech.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvenVzc2FzdGVscXlvbHdlZWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzU2NDUsImV4cCI6MjA2MzkxMTY0NX0.nd3fRx2RC1mat9nsqgXw_-TCpXQetmD5IwWlUN84b7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);